"""add revoked at to account tokens

Revision ID: d9a4e5382af9
Revises: a02b8104a3de
Create Date: 2026-07-17 07:52:18.947536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9a4e5382af9'
down_revision: Union[str, Sequence[str], None] = 'a02b8104a3de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_tokens', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_tokens', 'revoked_at')
    # ### end Alembic commands ###
